### ISSUE TITLE
Pushing bundled images

### ISSUE THREAD

**Issue by ewianda** [hunshcn/rule_oci_bundle#2]
I am trying to use this rule to push a bundle and I am getting 

```
bazel run //example:push
INFO: Analyzed target //example:push (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //example:push up-to-date:
  bazel-bin/example/push_push.sh
INFO: Elapsed time: 0.056s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/example/push_push.sh
Error: layout contains 2 entries, consider --index
```

**Comment by hunshcn** [comment]
need https://github.com/google/go-containerregistry/pull/1787

**Comment by ewianda** [comment]
Thanks for pointing that out. Is there any workaround ?

**Comment by hunshcn** [comment]
apply patch to crane, compile and find a place to store it. Then patch rules_oci to use patched crane.

I remember this pr as if it was based on 1.5.2.
Due to the lack of review for too long, conflicts have occurred at present.
I can rebase tomorrow.

**Comment by hunshcn** [comment]
The original repo was prepared for this pr, and not being able to get a review was an unanticipated event.

**Comment by ewianda** [comment]
Got it, thanks

**Comment by hunshcn** [comment]
> apply patch to crane, compile and find a place to store it. Then patch rules_oci to use patched crane.
> 
> I remember this pr as if it was based on 1.5.2. Due to the lack of review for too long, conflicts have occurred at present. I can rebase tomorrow.

done
